"""initial migration

Revision ID: 1751639a973d
Revises:
Create Date: 2026-07-16 00:32:36.396163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1751639a973d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre completo del remitente'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Correo electronico de contacto'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Telefono de contacto (opcional)'),
    sa.Column('service', sa.String(length=50), nullable=False, comment='Servicio de interes: compra, venta, renta, asesoria'),
    sa.Column('message', sa.Text(), nullable=False, comment='Mensaje o consulta del visitante'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado: new, contacted, closed'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_inquiries_email'), 'contact_inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_contact_inquiries_id'), 'contact_inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_contact_inquiries_status'), 'contact_inquiries', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nombre del rol (admin, advisor, client)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='Nombre completo del usuario'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email único del usuario'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Teléfono de contacto'),
    sa.Column('password_hash', sa.String(), nullable=False, comment='Hash bcrypt de la contraseña'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='FK al rol del usuario'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Si el usuario está activo en el sistema'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='Si el email del usuario ha sido verificado'),
    sa.Column('user_preferences', sa.JSON(), nullable=True, comment='Preferencias de notificación del usuario (JSON)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Usuario que realizó la acción'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Tipo de acción: login, property_created, property_viewed, etc.'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='Tipo de entidad: property, appointment, user, message'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='ID de la entidad afectada'),
    sa.Column('details', sa.Text(), nullable=True, comment='Detalles adicionales (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Dirección IP del usuario'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('advisors',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK a users (One-to-One)'),
    sa.Column('license_number', sa.String(length=50), nullable=True, comment='Número de licencia profesional'),
    sa.Column('agency_name', sa.String(length=100), nullable=True, comment='Nombre de la agencia inmobiliaria'),
    sa.Column('profile_picture', sa.String(), nullable=True, comment='URL de la foto de perfil del asesor'),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), nullable=True, comment='Calificación del asesor (0.00 - 5.00)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.create_table('client_advisor_assignments',
    sa.Column('client_id', sa.Integer(), nullable=False, comment='FK al cliente'),
    sa.Column('advisor_id', sa.Integer(), nullable=False, comment='FK al asesor'),
    sa.Column('assigned_date', sa.TIMESTAMP(), nullable=False, comment='Fecha de asignación'),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True, comment='Fecha de finalización'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Estado: active, inactive'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas sobre la asignación'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_advisor_assignments_advisor_id'), 'client_advisor_assignments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_client_advisor_assignments_client_id'), 'client_advisor_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_advisor_assignments_id'), 'client_advisor_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_client_advisor_assignments_status'), 'client_advisor_assignments', ['status'], unique=False)
    op.create_table('properties',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título de la propiedad'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción detallada de la propiedad'),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), nullable=False, comment='Precio en la moneda local'),
    sa.Column('property_type', sa.String(length=50), nullable=False, comment='Tipo: house, apartment, land, commercial'),
    sa.Column('transaction_type', sa.String(length=50), nullable=True, comment='Operación: sale o rent'),
    sa.Column('address', sa.Text(), nullable=False, comment='Dirección completa'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='Ciudad'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Coordenada latitud para el mapa'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Coordenada longitud para el mapa'),
    sa.Column('bedrooms', sa.Integer(), nullable=True, comment='Número de recámaras'),
    sa.Column('bathrooms', sa.Integer(), nullable=True, comment='Número de baños'),
    sa.Column('square_meters', sa.Integer(), nullable=True, comment='Metros cuadrados de construcción'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Estado: pending, approved, rejected, sold'),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True, comment='FK al usuario que publicó la propiedad'),
    sa.Column('advisor_id', sa.Integer(), nullable=True, comment='FK al asesor asignado'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('client_id', sa.Integer(), nullable=False, comment='FK al usuario cliente'),
    sa.Column('advisor_id', sa.Integer(), nullable=False, comment='FK al asesor'),
    sa.Column('property_id', sa.Integer(), nullable=True, comment='FK a la propiedad (opcional)'),
    sa.Column('appointment_type', sa.String(length=50), nullable=True, comment='Tipo: viewing (ver propiedad) o inspection (inspección)'),
    sa.Column('scheduled_date', sa.TIMESTAMP(), nullable=False, comment='Fecha y hora programada'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Estado: pending, confirmed, completed, cancelled'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas adicionales sobre la cita'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_advisor_id'), 'appointments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True, comment='FK a la propiedad asociada (opcional)'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'advisor_id', name='uq_conversation_user_advisor')
    )
    op.create_index(op.f('ix_conversations_advisor_id'), 'conversations', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK al usuario'),
    sa.Column('property_id', sa.Integer(), nullable=False, comment='FK a la propiedad'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='unique_favorite')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_property_id'), 'favorites', ['property_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Usuario que recibe la notificación'),
    sa.Column('property_id', sa.Integer(), nullable=True, comment='Propiedad relacionada (opcional)'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Tipo: advisor_assigned, approved, rejected, sold, property_updated'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título corto de la notificación'),
    sa.Column('message', sa.Text(), nullable=False, comment='Mensaje detallado de la notificación'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='Si la notificación ha sido leída'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('post_sale_followups',
    sa.Column('property_id', sa.Integer(), nullable=False, comment='FK a la propiedad vendida'),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='FK al cliente'),
    sa.Column('advisor_id', sa.Integer(), nullable=True, comment='FK al asesor responsable'),
    sa.Column('sale_date', sa.TIMESTAMP(), nullable=False, comment='Fecha de la venta/renta'),
    sa.Column('followup_type', sa.String(length=50), nullable=False, comment='Tipo: satisfaction_survey, check_in_call, referral_request, maintenance_reminder'),
    sa.Column('scheduled_date', sa.TIMESTAMP(), nullable=False, comment='Fecha programada para el seguimiento'),
    sa.Column('completed_date', sa.TIMESTAMP(), nullable=True, comment='Fecha en que se completó el seguimiento'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Estado: pending, completed, skipped'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas adicionales del seguimiento'),
    sa.Column('satisfaction_score', sa.SmallInteger(), nullable=True, comment='Puntuación de satisfacción (1-5)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_sale_followups_client_id'), 'post_sale_followups', ['client_id'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_followup_type'), 'post_sale_followups', ['followup_type'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_id'), 'post_sale_followups', ['id'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_property_id'), 'post_sale_followups', ['property_id'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_scheduled_date'), 'post_sale_followups', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_status'), 'post_sale_followups', ['status'], unique=False)
    op.create_table('property_images',
    sa.Column('property_id', sa.Integer(), nullable=False, comment='FK a la propiedad'),
    sa.Column('image_url', sa.String(), nullable=False, comment='URL o ruta del archivo de imagen'),
    sa.Column('label', sa.String(length=100), nullable=True, comment='Nombre visible del extra, por ejemplo Cocina o Patio'),
    sa.Column('image_type', sa.String(length=50), nullable=False, comment='Tipo de imagen: general, extra, bedroom o bathroom'),
    sa.Column('is_extra', sa.Boolean(), nullable=False, comment='Si la imagen pertenece al apartado de extras'),
    sa.Column('is_main', sa.Boolean(), nullable=True, comment='Si es la imagen principal de la propiedad'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_id'), 'property_images', ['id'], unique=False)
    op.create_index(op.f('ix_property_images_image_type'), 'property_images', ['image_type'], unique=False)
    op.create_index(op.f('ix_property_images_is_extra'), 'property_images', ['is_extra'], unique=False)
    op.create_index(op.f('ix_property_images_is_main'), 'property_images', ['is_main'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.execute("""
        INSERT INTO roles (id, name) VALUES
        (1, 'admin'),
        (2, 'advisor'),
        (3, 'client')
        ON CONFLICT (id) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_is_main'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_is_extra'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_image_type'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_post_sale_followups_status'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_scheduled_date'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_property_id'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_id'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_followup_type'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_client_id'), table_name='post_sale_followups')
    op.drop_table('post_sale_followups')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_property_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_advisor_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_advisor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_client_advisor_assignments_status'), table_name='client_advisor_assignments')
    op.drop_index(op.f('ix_client_advisor_assignments_id'), table_name='client_advisor_assignments')
    op.drop_index(op.f('ix_client_advisor_assignments_client_id'), table_name='client_advisor_assignments')
    op.drop_index(op.f('ix_client_advisor_assignments_advisor_id'), table_name='client_advisor_assignments')
    op.drop_table('client_advisor_assignments')
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.drop_table('advisors')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_contact_inquiries_status'), table_name='contact_inquiries')
    op.drop_index(op.f('ix_contact_inquiries_id'), table_name='contact_inquiries')
    op.drop_index(op.f('ix_contact_inquiries_email'), table_name='contact_inquiries')
    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###
