"""add contact_inquiries table

Revision ID: 3643a157ea4e
Revises: 50117421c43a
Create Date: 2026-06-02 20:56:28.645830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3643a157ea4e'
down_revision: Union[str, None] = '50117421c43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre completo del remitente'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Correo electronico de contacto'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Telefono de contacto (opcional)'),
    sa.Column('service', sa.String(length=50), nullable=False, comment='Servicio de interes: compra, venta, renta, asesoria'),
    sa.Column('message', sa.Text(), nullable=False, comment='Mensaje o consulta del visitante'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado: new, contacted, closed'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_inquiries_email'), 'contact_inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_contact_inquiries_id'), 'contact_inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_contact_inquiries_status'), 'contact_inquiries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_inquiries_status'), table_name='contact_inquiries')
    op.drop_index(op.f('ix_contact_inquiries_id'), table_name='contact_inquiries')
    op.drop_index(op.f('ix_contact_inquiries_email'), table_name='contact_inquiries')
    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###
