"""add notification_preferences table

Revision ID: 50117421c43a
Revises: 431acf2b8142
Create Date: 2026-05-22 16:46:59.369072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50117421c43a'
down_revision: Union[str, None] = '431acf2b8142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', name='uq_user_notification_type')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Usuario que realizó la acción',
               existing_nullable=True)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='Tipo de acción: login, property_created, property_viewed, etc.',
               existing_nullable=False)
    op.alter_column('activity_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo de entidad: property, appointment, user, message',
               existing_nullable=True)
    op.alter_column('activity_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               comment='ID de la entidad afectada',
               existing_nullable=True)
    op.alter_column('activity_logs', 'details',
               existing_type=sa.TEXT(),
               comment='Detalles adicionales (JSON)',
               existing_nullable=True)
    op.alter_column('activity_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Dirección IP del usuario',
               existing_nullable=True)
    op.alter_column('advisors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='FK a users (One-to-One)')
    op.alter_column('advisors', 'license_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Número de licencia profesional',
               existing_nullable=True)
    op.alter_column('advisors', 'agency_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre de la agencia inmobiliaria',
               existing_nullable=True)
    op.alter_column('advisors', 'profile_picture',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='URL de la foto de perfil del asesor',
               existing_nullable=True)
    op.alter_column('advisors', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='Calificación del asesor (0.00 - 5.00)',
               existing_nullable=True,
               existing_server_default=sa.text('5.00'))
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.drop_table_comment(
        'advisors',
        existing_comment='Perfil extendido para asesores inmobiliarios',
        schema=None
    )
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               comment='FK al usuario cliente',
               existing_nullable=False)
    op.alter_column('appointments', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment='FK al asesor',
               existing_nullable=False)
    op.alter_column('appointments', 'property_id',
               existing_type=sa.INTEGER(),
               comment='FK a la propiedad (opcional)',
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo: viewing (ver propiedad) o inspection (inspección)',
               existing_nullable=True,
               existing_server_default=sa.text("'viewing'::character varying"))
    op.alter_column('appointments', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha y hora programada',
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Estado: pending, confirmed, completed, cancelled',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'notes',
               existing_type=sa.TEXT(),
               comment='Notas adicionales sobre la cita',
               existing_nullable=True)
    op.drop_index('idx_appointments_advisor_id', table_name='appointments')
    op.drop_index('idx_appointments_client_id', table_name='appointments')
    op.drop_index('idx_appointments_scheduled_date', table_name='appointments')
    op.drop_index('idx_appointments_status', table_name='appointments')
    op.create_index(op.f('ix_appointments_advisor_id'), 'appointments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.drop_table_comment(
        'appointments',
        existing_comment='Citas programadas entre clientes y asesores',
        schema=None
    )
    op.alter_column('client_advisor_assignments', 'client_id',
               existing_type=sa.INTEGER(),
               comment='FK al cliente',
               existing_nullable=False)
    op.alter_column('client_advisor_assignments', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment='FK al asesor',
               existing_nullable=False)
    op.alter_column('client_advisor_assignments', 'assigned_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de asignación',
               existing_nullable=False)
    op.alter_column('client_advisor_assignments', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de finalización',
               existing_nullable=True)
    op.alter_column('client_advisor_assignments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Estado: active, inactive',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('client_advisor_assignments', 'notes',
               existing_type=sa.TEXT(),
               comment='Notas sobre la asignación',
               existing_nullable=True)
    op.drop_index('idx_client_advisor_advisor_id', table_name='client_advisor_assignments')
    op.drop_index('idx_client_advisor_client_id', table_name='client_advisor_assignments')
    op.drop_index('idx_client_advisor_status', table_name='client_advisor_assignments')
    op.create_index(op.f('ix_client_advisor_assignments_advisor_id'), 'client_advisor_assignments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_client_advisor_assignments_client_id'), 'client_advisor_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_advisor_assignments_id'), 'client_advisor_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_client_advisor_assignments_status'), 'client_advisor_assignments', ['status'], unique=False)
    op.drop_table_comment(
        'client_advisor_assignments',
        existing_comment='Relación formal entre clientes y asesores inmobiliarios',
        schema=None
    )
    op.alter_column('conversations', 'property_id',
               existing_type=sa.INTEGER(),
               comment='FK a la propiedad asociada (opcional)',
               existing_nullable=True)
    op.drop_constraint('conversations_user_id_advisor_id_key', 'conversations', type_='unique')
    op.drop_index('idx_conversations_advisor', table_name='conversations')
    op.drop_index('idx_conversations_last_message', table_name='conversations')
    op.drop_index('idx_conversations_user', table_name='conversations')
    op.create_index(op.f('ix_conversations_advisor_id'), 'conversations', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_advisor_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'advisors', ['advisor_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               comment='FK al usuario',
               existing_nullable=False)
    op.alter_column('favorites', 'property_id',
               existing_type=sa.INTEGER(),
               comment='FK a la propiedad',
               existing_nullable=False)
    op.drop_index('idx_favorites_property_id', table_name='favorites')
    op.drop_index('idx_favorites_user_id', table_name='favorites')
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_property_id'), 'favorites', ['property_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.drop_table_comment(
        'favorites',
        existing_comment='Propiedades guardadas como favoritas por los usuarios',
        schema=None
    )
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_index('idx_messages_is_read', table_name='messages', postgresql_where='(is_read = false)')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Usuario que recibe la notificación',
               existing_nullable=False)
    op.alter_column('notifications', 'property_id',
               existing_type=sa.INTEGER(),
               comment='Propiedad relacionada (opcional)',
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo: advisor_assigned, approved, rejected, sold, property_updated',
               existing_nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Título corto de la notificación',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='Mensaje detallado de la notificación',
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Si la notificación ha sido leída',
               existing_server_default=sa.text('false'))
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_user_id_is_read', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('notifications_property_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'properties', ['property_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('post_sale_followups', 'property_id',
               existing_type=sa.INTEGER(),
               comment='FK a la propiedad vendida',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'client_id',
               existing_type=sa.INTEGER(),
               comment='FK al cliente',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment='FK al asesor responsable',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de la venta/renta',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'followup_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo: satisfaction_survey, check_in_call, referral_request, maintenance_reminder',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha programada para el seguimiento',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'completed_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha en que se completó el seguimiento',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Estado: pending, completed, skipped',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_sale_followups', 'notes',
               existing_type=sa.TEXT(),
               comment='Notas adicionales del seguimiento',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'satisfaction_score',
               existing_type=sa.SMALLINT(),
               comment='Puntuación de satisfacción (1-5)',
               existing_nullable=True)
    op.drop_index('idx_post_sale_advisor_id', table_name='post_sale_followups')
    op.drop_index('idx_post_sale_client_id', table_name='post_sale_followups')
    op.drop_index('idx_post_sale_followup_type', table_name='post_sale_followups')
    op.drop_index('idx_post_sale_property_id', table_name='post_sale_followups')
    op.drop_index('idx_post_sale_scheduled_date', table_name='post_sale_followups')
    op.drop_index('idx_post_sale_status', table_name='post_sale_followups')
    op.create_index(op.f('ix_post_sale_followups_client_id'), 'post_sale_followups', ['client_id'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_followup_type'), 'post_sale_followups', ['followup_type'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_id'), 'post_sale_followups', ['id'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_property_id'), 'post_sale_followups', ['property_id'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_scheduled_date'), 'post_sale_followups', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_post_sale_followups_status'), 'post_sale_followups', ['status'], unique=False)
    op.drop_table_comment(
        'post_sale_followups',
        existing_comment='Seguimiento automatizado post-venta (encuestas, llamadas, referidos, mantenimiento)',
        schema=None
    )
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Título de la propiedad',
               existing_nullable=False)
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               comment='Descripción detallada de la propiedad',
               existing_nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Precio en la moneda local',
               existing_nullable=False)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo: house, apartment, land, commercial',
               existing_nullable=False)
    op.alter_column('properties', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Operación: sale o rent',
               existing_nullable=True,
               existing_server_default=sa.text("'sale'::character varying"))
    op.alter_column('properties', 'address',
               existing_type=sa.TEXT(),
               comment='Dirección completa',
               existing_nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='Ciudad',
               existing_nullable=False)
    op.alter_column('properties', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Coordenada latitud para el mapa',
               existing_nullable=True)
    op.alter_column('properties', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Coordenada longitud para el mapa',
               existing_nullable=True)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               comment='Número de recámaras',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               comment='Número de baños',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('properties', 'square_meters',
               existing_type=sa.INTEGER(),
               comment='Metros cuadrados de construcción',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('properties', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Estado: pending, approved, rejected, sold',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('properties', 'submitted_by_user_id',
               existing_type=sa.INTEGER(),
               comment='FK al usuario que publicó la propiedad',
               existing_nullable=True)
    op.alter_column('properties', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment='FK al asesor asignado',
               existing_nullable=True)
    op.drop_index('idx_properties_advisor_id', table_name='properties')
    op.drop_index('idx_properties_city', table_name='properties')
    op.drop_index('idx_properties_price', table_name='properties')
    op.drop_index('idx_properties_property_type', table_name='properties')
    op.drop_index('idx_properties_search_vector', table_name='properties', postgresql_using='gin')
    op.drop_index('idx_properties_status', table_name='properties')
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.drop_table_comment(
        'properties',
        existing_comment='Propiedades listadas en el sistema',
        schema=None
    )
    op.drop_column('properties', 'search_vector')
    op.alter_column('property_images', 'property_id',
               existing_type=sa.INTEGER(),
               comment='FK a la propiedad',
               existing_nullable=False)
    op.alter_column('property_images', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='URL o ruta del archivo de imagen',
               existing_nullable=False)
    op.alter_column('property_images', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre visible del extra, por ejemplo Cocina o Patio',
               existing_nullable=True)
    op.alter_column('property_images', 'image_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo de imagen: general, extra, bedroom o bathroom',
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('property_images', 'is_extra',
               existing_type=sa.BOOLEAN(),
               comment='Si la imagen pertenece al apartado de extras',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('property_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               comment='Si es la imagen principal de la propiedad',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_property_images_image_type', table_name='property_images')
    op.drop_index('idx_property_images_is_extra', table_name='property_images')
    op.drop_index('idx_property_images_is_main', table_name='property_images')
    op.drop_index('idx_property_images_property_id', table_name='property_images')
    op.create_index(op.f('ix_property_images_id'), 'property_images', ['id'], unique=False)
    op.create_index(op.f('ix_property_images_image_type'), 'property_images', ['image_type'], unique=False)
    op.create_index(op.f('ix_property_images_is_extra'), 'property_images', ['is_extra'], unique=False)
    op.create_index(op.f('ix_property_images_is_main'), 'property_images', ['is_main'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.drop_table_comment(
        'property_images',
        existing_comment='Galería de imágenes de las propiedades',
        schema=None
    )
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Nombre del rol (admin, advisor, client)',
               existing_nullable=False)
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_table_comment(
        'roles',
        existing_comment='Tipos de usuarios del sistema',
        schema=None
    )
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre completo del usuario',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='Email único del usuario',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Teléfono de contacto',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='Hash bcrypt de la contraseña',
               existing_nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               comment='FK al rol del usuario',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Si el usuario está activo en el sistema',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_table_comment(
        'users',
        existing_comment='Usuarios generales del sistema',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Usuarios generales del sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si el usuario está activo en el sistema',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al rol del usuario',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Hash bcrypt de la contraseña',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Teléfono de contacto',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Email único del usuario',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre completo del usuario',
               existing_nullable=False)
    op.create_table_comment(
        'roles',
        'Tipos de usuarios del sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nombre del rol (admin, advisor, client)',
               existing_nullable=False)
    op.create_table_comment(
        'property_images',
        'Galería de imágenes de las propiedades',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_is_main'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_is_extra'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_image_type'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_id'), table_name='property_images')
    op.create_index('idx_property_images_property_id', 'property_images', ['property_id'], unique=False)
    op.create_index('idx_property_images_is_main', 'property_images', ['is_main'], unique=False)
    op.create_index('idx_property_images_is_extra', 'property_images', ['is_extra'], unique=False)
    op.create_index('idx_property_images_image_type', 'property_images', ['image_type'], unique=False)
    op.alter_column('property_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si es la imagen principal de la propiedad',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('property_images', 'is_extra',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si la imagen pertenece al apartado de extras',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('property_images', 'image_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo de imagen: general, extra, bedroom o bathroom',
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('property_images', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre visible del extra, por ejemplo Cocina o Patio',
               existing_nullable=True)
    op.alter_column('property_images', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='URL o ruta del archivo de imagen',
               existing_nullable=False)
    op.alter_column('property_images', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a la propiedad',
               existing_nullable=False)
    op.add_column('properties', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('(((setweight(to_tsvector(\'spanish\'::regconfig, (COALESCE(title, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'spanish\'::regconfig, COALESCE(description, \'\'::text)), \'B\'::"char")) || setweight(to_tsvector(\'spanish\'::regconfig, (COALESCE(city, \'\'::character varying))::text), \'C\'::"char")) || setweight(to_tsvector(\'spanish\'::regconfig, (COALESCE(property_type, \'\'::character varying))::text), \'D\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_table_comment(
        'properties',
        'Propiedades listadas en el sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.create_index('idx_properties_status', 'properties', ['status'], unique=False)
    op.create_index('idx_properties_search_vector', 'properties', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_properties_property_type', 'properties', ['property_type'], unique=False)
    op.create_index('idx_properties_price', 'properties', ['price'], unique=False)
    op.create_index('idx_properties_city', 'properties', ['city'], unique=False)
    op.create_index('idx_properties_advisor_id', 'properties', ['advisor_id'], unique=False)
    op.alter_column('properties', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al asesor asignado',
               existing_nullable=True)
    op.alter_column('properties', 'submitted_by_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al usuario que publicó la propiedad',
               existing_nullable=True)
    op.alter_column('properties', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Estado: pending, approved, rejected, sold',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('properties', 'square_meters',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Metros cuadrados de construcción',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número de baños',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número de recámaras',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('properties', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Coordenada longitud para el mapa',
               existing_nullable=True)
    op.alter_column('properties', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Coordenada latitud para el mapa',
               existing_nullable=True)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Ciudad',
               existing_nullable=False)
    op.alter_column('properties', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Dirección completa',
               existing_nullable=False)
    op.alter_column('properties', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Operación: sale o rent',
               existing_nullable=True,
               existing_server_default=sa.text("'sale'::character varying"))
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo: house, apartment, land, commercial',
               existing_nullable=False)
    op.alter_column('properties', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Precio en la moneda local',
               existing_nullable=False)
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descripción detallada de la propiedad',
               existing_nullable=True)
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Título de la propiedad',
               existing_nullable=False)
    op.create_table_comment(
        'post_sale_followups',
        'Seguimiento automatizado post-venta (encuestas, llamadas, referidos, mantenimiento)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_post_sale_followups_status'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_scheduled_date'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_property_id'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_id'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_followup_type'), table_name='post_sale_followups')
    op.drop_index(op.f('ix_post_sale_followups_client_id'), table_name='post_sale_followups')
    op.create_index('idx_post_sale_status', 'post_sale_followups', ['status'], unique=False)
    op.create_index('idx_post_sale_scheduled_date', 'post_sale_followups', ['scheduled_date'], unique=False)
    op.create_index('idx_post_sale_property_id', 'post_sale_followups', ['property_id'], unique=False)
    op.create_index('idx_post_sale_followup_type', 'post_sale_followups', ['followup_type'], unique=False)
    op.create_index('idx_post_sale_client_id', 'post_sale_followups', ['client_id'], unique=False)
    op.create_index('idx_post_sale_advisor_id', 'post_sale_followups', ['advisor_id'], unique=False)
    op.alter_column('post_sale_followups', 'satisfaction_score',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Puntuación de satisfacción (1-5)',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notas adicionales del seguimiento',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Estado: pending, completed, skipped',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_sale_followups', 'completed_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha en que se completó el seguimiento',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha programada para el seguimiento',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'followup_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo: satisfaction_survey, check_in_call, referral_request, maintenance_reminder',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de la venta/renta',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al asesor responsable',
               existing_nullable=True)
    op.alter_column('post_sale_followups', 'client_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al cliente',
               existing_nullable=False)
    op.alter_column('post_sale_followups', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a la propiedad vendida',
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_property_id_fkey', 'notifications', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('idx_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', [sa.text('created_at DESC')], unique=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Si la notificación ha sido leída',
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mensaje detallado de la notificación',
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Título corto de la notificación',
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo: advisor_assigned, approved, rejected, sold, property_updated',
               existing_nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('notifications', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Propiedad relacionada (opcional)',
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Usuario que recibe la notificación',
               existing_nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_is_read', 'messages', ['is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_table_comment(
        'favorites',
        'Propiedades guardadas como favoritas por los usuarios',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_property_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.create_index('idx_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index('idx_favorites_property_id', 'favorites', ['property_id'], unique=False)
    op.alter_column('favorites', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a la propiedad',
               existing_nullable=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al usuario',
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_advisor_id_fkey', 'conversations', 'advisors', ['advisor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_advisor_id'), table_name='conversations')
    op.create_index('idx_conversations_user', 'conversations', ['user_id'], unique=False)
    op.create_index('idx_conversations_last_message', 'conversations', [sa.text('last_message_at DESC NULLS LAST')], unique=False)
    op.create_index('idx_conversations_advisor', 'conversations', ['advisor_id'], unique=False)
    op.create_unique_constraint('conversations_user_id_advisor_id_key', 'conversations', ['user_id', 'advisor_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('conversations', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a la propiedad asociada (opcional)',
               existing_nullable=True)
    op.create_table_comment(
        'client_advisor_assignments',
        'Relación formal entre clientes y asesores inmobiliarios',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_client_advisor_assignments_status'), table_name='client_advisor_assignments')
    op.drop_index(op.f('ix_client_advisor_assignments_id'), table_name='client_advisor_assignments')
    op.drop_index(op.f('ix_client_advisor_assignments_client_id'), table_name='client_advisor_assignments')
    op.drop_index(op.f('ix_client_advisor_assignments_advisor_id'), table_name='client_advisor_assignments')
    op.create_index('idx_client_advisor_status', 'client_advisor_assignments', ['status'], unique=False)
    op.create_index('idx_client_advisor_client_id', 'client_advisor_assignments', ['client_id'], unique=False)
    op.create_index('idx_client_advisor_advisor_id', 'client_advisor_assignments', ['advisor_id'], unique=False)
    op.alter_column('client_advisor_assignments', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notas sobre la asignación',
               existing_nullable=True)
    op.alter_column('client_advisor_assignments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Estado: active, inactive',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('client_advisor_assignments', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de finalización',
               existing_nullable=True)
    op.alter_column('client_advisor_assignments', 'assigned_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de asignación',
               existing_nullable=False)
    op.alter_column('client_advisor_assignments', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al asesor',
               existing_nullable=False)
    op.alter_column('client_advisor_assignments', 'client_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al cliente',
               existing_nullable=False)
    op.create_table_comment(
        'appointments',
        'Citas programadas entre clientes y asesores',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_advisor_id'), table_name='appointments')
    op.create_index('idx_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('idx_appointments_scheduled_date', 'appointments', ['scheduled_date'], unique=False)
    op.create_index('idx_appointments_client_id', 'appointments', ['client_id'], unique=False)
    op.create_index('idx_appointments_advisor_id', 'appointments', ['advisor_id'], unique=False)
    op.alter_column('appointments', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notas adicionales sobre la cita',
               existing_nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Estado: pending, confirmed, completed, cancelled',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha y hora programada',
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo: viewing (ver propiedad) o inspection (inspección)',
               existing_nullable=True,
               existing_server_default=sa.text("'viewing'::character varying"))
    op.alter_column('appointments', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a la propiedad (opcional)',
               existing_nullable=True)
    op.alter_column('appointments', 'advisor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al asesor',
               existing_nullable=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK al usuario cliente',
               existing_nullable=False)
    op.create_table_comment(
        'advisors',
        'Perfil extendido para asesores inmobiliarios',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.alter_column('advisors', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='Calificación del asesor (0.00 - 5.00)',
               existing_nullable=True,
               existing_server_default=sa.text('5.00'))
    op.alter_column('advisors', 'profile_picture',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='URL de la foto de perfil del asesor',
               existing_nullable=True)
    op.alter_column('advisors', 'agency_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre de la agencia inmobiliaria',
               existing_nullable=True)
    op.alter_column('advisors', 'license_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número de licencia profesional',
               existing_nullable=True)
    op.alter_column('advisors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='FK a users (One-to-One)')
    op.alter_column('activity_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Dirección IP del usuario',
               existing_nullable=True)
    op.alter_column('activity_logs', 'details',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detalles adicionales (JSON)',
               existing_nullable=True)
    op.alter_column('activity_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID de la entidad afectada',
               existing_nullable=True)
    op.alter_column('activity_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo de entidad: property, appointment, user, message',
               existing_nullable=True)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tipo de acción: login, property_created, property_viewed, etc.',
               existing_nullable=False)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Usuario que realizó la acción',
               existing_nullable=True)
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
