"""add performance indexes

Revision ID: 6465055488c0
Revises: 682994230f39
Create Date: 2026-09-12 14:30:04.624294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6465055488c0'
down_revision: Union[str, None] = '682994230f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_property_id'), 'appointments', ['property_id'], unique=False)
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_properties_advisor_id'), 'properties', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_properties_submitted_by_user_id'), 'properties', ['submitted_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_submitted_by_user_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_advisor_id'), table_name='properties')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_index(op.f('ix_appointments_property_id'), table_name='appointments')
    # ### end Alembic commands ###
